name: UNjobs Bangladesh watcher

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (UTC)
  workflow_dispatch:         # lets you run it manually anytime

permissions:
  contents: write            # needed to commit seen_jobs.json back to the repo

jobs:
  crawl:
    runs-on: ubuntu-latest
    concurrency:
      group: unjobs-watcher
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv

      - name: Run watcher (single check)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          SMTP_HOST:          ${{ secrets.SMTP_HOST }}
          SMTP_PORT:          ${{ secrets.SMTP_PORT }}
          SMTP_USER:          ${{ secrets.SMTP_USER }}
          SMTP_PASS:          ${{ secrets.SMTP_PASS }}
          ALERT_EMAIL:        ${{ secrets.ALERT_EMAIL }}
        run: |
          python unjobs_watcher.py --once

      - name: Persist seen list
        run: |
          if [ -f seen_jobs.json ]; then
            git config user.name "unjobs-bot"
            git config user.email "actions@users.noreply.github.com"
            git add seen_jobs.json
            git commit -m "update seen list [skip ci]" || true
            git push || true
          fi
